import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'package:vendora/core/services/storage_service.dart';
import 'package:vendora/core/services/firebase/app_notification_initializer.dart';
import 'firebase_options.dart';

import 'app.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase init (generated by flutterfire configure)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  ); // [web:38][web:35]

  // Your local init
  await StorageService.init();
  await AppNotificationInitializer.init();

  // Initialize EasyLoading - moved to app.dart MaterialApp builder
  // EasyLoading.init();

  runApp(const MyApp());
}
